baseURL = "/"
languageCode = "en-us"
title = "Araw Seekers"

[permalinks]
	blog = "/:filename/"

[params]
	homeText = "(A)typical Experiences via Photosynthesis"

[menu]
	[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
	[[menu.main]]
